In [3]:
import numpy as np

# Bước 1: Tạo array arr có kích thước 3x3 với các giá trị True
arr = np.full((3, 3), True, dtype=bool)

# Bước 2: Tạo array 1 chiều arr_1D
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Chuyển arr_1D thành array 2 chiều 3x3 và hoán đổi cột 1 và cột 3
arr_2D = arr_1D.reshape(3, 3)[:, [2, 1, 0]]

# Bước 3: Hoán đổi dòng 1 và dòng 2
arr_2D[[0, 1]] = arr_2D[[1, 0]]

# Bước 4: Đảo ngược các dòng của arr_2D
arr_2D = np.flipud(arr_2D)

# Bước 5: Đảo ngược các cột của arr_2D
arr_2D = np.fliplr(arr_2D)

# Bước 6: Tạo array arr_2D_null và kiểm tra giá trị rỗng
arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])
has_nan = np.isnan(arr_2D_null).any()

# Bước 7: Thay thế giá trị rỗng (nan) bằng 0
arr_2D_null[np.isnan(arr_2D_null)] = 0

# In kết quả
print("Bước 1: arr:\n", arr)
print("Bước 2: arr_2D:\n", arr_2D)
print("Bước 6: Có giá trị rỗng trong arr_2D_null:", has_nan)
print("Bước 7: arr_2D_null (sau khi thay thế giá trị rỗng):\n", arr_2D_null)


Bước 1: arr:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Bước 2: arr_2D:
 [[6 7 8]
 [0 1 2]
 [3 4 5]]
Bước 6: Có giá trị rỗng trong arr_2D_null: True
Bước 7: arr_2D_null (sau khi thay thế giá trị rỗng):
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
